[package]
name = "vt"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subprocess = "0.2"
tokio = { version = "1", features = ["full"] }
clap = "4.0"
colored = "2.1.0"

