version: '3.8'
services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juiceshop
    ports:
      - "3000:3000"
    networks:
      - vulnerabilitytargets_default

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    networks:
      - vulnerabilitytargets_default

  mutillidae:
    image: citizenstig/nowasp
    container_name: mutillidae
    ports:
      - "8081:80"
    networks:
      - vulnerabilitytargets_default

  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    ports:
      - "8082:80"
    networks:
      - vulnerabilitytargets_default

  nodegoat:
    image: nodegoat/nodegoat
    container_name: nodegoat
    ports:
      - "4000:4000"
    networks:
      - vulnerabilitytargets_default

  metasploitable:
    image: twelvesec/metasploitable
    container_name: metasploitable
    ports:
      - "2222:22"
      - "8023:23"
      - "8083:80"
    networks:
      - vulnerabilitytargets_default

  broken-crystals:
    image: owaspbrokencrystals/brokencrystals
    container_name: broken-crystals
    ports:
      - "5000:5000"
    networks:
      - vulnerabilitytargets_default

  dvws:
    image: vgartvichwallarm/dvws
    container_name: dvws
    ports:
      - "8888:80"
    networks:
      - vulnerabilitytargets_default

networks:
  vulnerabilitytargets_default:
    driver: bridge
